name: Sync Fork Repository

on:
  push:
    branches: [ deploy ]
  workflow_dispatch: # 수동 실행도 가능

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    # 원본 리포에서만 실행
    if: github.repository == 'erica-likelion/fall-festival-client'
    
    steps:
      - name: Sync fork using GitHub API
        run: |
          # GitHub API를 사용해서 포크 리포지토리 동기화 (GitHub의 "Sync fork" 버튼과 동일)
          response=$(curl -s -X POST \
            -H "Authorization: token ${{ secrets.FORK_SYNC_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/pdjdev/fall-festival-client/merge-upstream \
            -d '{"branch":"main"}')
          
          echo "API Response: $response"
